package org.arosso.routines.egcs;
import java.io.IOException;
import java.util.Properties;

import org.arosso.model.BuildingModel;
import org.arosso.model.Passenger;
import org.arosso.sim.RoutineManager;
import org.arosso.sim.SimulationRoutine;
import org.arosso.sim.TrafficModel;
import org.arosso.util.PropertiesBroker;
import org.arosso.util.PropertiesBroker.PROP_SET;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

/**
 * File generated from the model::conventionalElevatorGroupController uml Class
 * Generated by the Acceleo 3 <i>UML to Java</i> generator.
 */


/**
 * Description of conventionalElevatorGroupController.
 */
public class ConventionalElevatorGroupController implements ElevatorGroupController {
    /**
     * Description of the property rutineManager.
     */
    public RoutineManager rutineManager = null;
    
    /**
     * Logger
     */
    Logger logger = LoggerFactory.getLogger(this.getClass());
    
    BuildingModel buildingModel;
    
    
    /**
     * The constructor.
     * @throws Exception 
     * @throws IOException 
     */
    public ConventionalElevatorGroupController() throws Exception {
    	super();
    	logger.debug("ConventionalElevatorGroupController created!");
    	buildingModel = BuildingModel.getInstance();
    }
    
    public void assignCalls(Passenger passenger) {
	    logger.info("Assinging calls of the building");	
    }
    
    /**
     * Description of the method assignCallToElevator.
     */
    public void assignCallToElevator() {
    	// Start of user code for method assignCallToElevator
    	// End of user code
    }
     
    /**
     * {@inheritDoc}
     * @see .ElevatorGroupController
     *
     */
    public void assignCall(Passenger passenger) {
	    logger.debug("Assinging calls of the building");	
	    
    }
    
    
    /**
     * Returns rutineManager.
     * @return rutineManager
     */
    public RoutineManager getRutineManager() {
    	return this.rutineManager;
    }
    
    /**
     * Sets a value to attribute rutineManager. 
     * @param newRutineManager
     */
    public void setRutineManager(RoutineManager newRutineManager) {
        this.rutineManager = newRutineManager;
    }
    
    
}
