package org.arosso.routines.egcs;
import java.io.IOException;
import java.util.Properties;

import org.arosso.model.BuildingModel;
import org.arosso.model.Passenger;
import org.arosso.sim.RoutineManager;
import org.arosso.sim.SimulationRoutine;
import org.arosso.sim.TrafficModel;
import org.arosso.util.PropertiesBroker;
import org.arosso.util.PropertiesBroker.PROP_SET;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

/**
 * File generated from the model::conventionalElevatorGroupController uml Class
 * Generated by the Acceleo 3 <i>UML to Java</i> generator.
 */


/**
 * Description of conventionalElevatorGroupController.
 */
public class ConventionalElevatorGroupController implements ElevatorGroupController {

    
    /**
     * Logger
     */
    Logger logger = LoggerFactory.getLogger(this.getClass());
    
    BuildingModel buildingModel;
    
    
    /**
     * The constructor.
     * @throws Exception 
     * @throws IOException 
     */
    public ConventionalElevatorGroupController() throws Exception {
    	super();
    	logger.debug("ConventionalElevatorGroupController created!");
    	buildingModel = BuildingModel.getInstance();
    }


	@Override
	public int assignCall(Passenger passenger) {
	    logger.debug("Assinging calls of the building");	
		return 0;
	}
     
    
    
}
