package org.arosso.routines.egcs;

import org.arosso.model.Passenger;

/**
 * File generated from the model::ElevatorGroupController uml Interface
 * Generated by the Acceleo 3 <i>UML to Java</i> generator.
 */


// Start of user code (user defined imports)	

// End of user code

/**
 * Description of ElevatorGroupController.
 */
public interface ElevatorGroupController {
	
	/**
	 * 
	 * @param passenger Passanger information
	 * @return elevator that won the call
	 */
	public int assignCall(Passenger passenger);

}
