package org.arosso.routines.egcs;

/**
 * File generated from the model::GenericEGController uml Class
 * Generated by the Acceleo 3 <i>UML to Java</i> generator.
 */


/**
 * Description of GenericEGController.
 */
public class GenericEGController {
    /**
     * Description of the property elevatorGroupController.
     */
    public ConventionalElevatorGroupController elevatorGroupController = null;
    
    // Start of user code (user defined attributes)
    
    // End of user code
    
    /**
     * The constructor.
     */
    public GenericEGController() {
    	// Start of user code constructor
    	super();
    	// End of user code
    }
    
    // Start of user code (user defined methods)
    
    // End of user code
    
    /**
     * Returns elevatorGroupController.
     * @return elevatorGroupController 
     */
    public ConventionalElevatorGroupController getElevatorGroupController() {
    	return this.elevatorGroupController;
    }
    
    /**
     * Sets a value to attribute elevatorGroupController. 
     * @param newElevatorGroupController 
     */
    public void setElevatorGroupController(ConventionalElevatorGroupController newElevatorGroupController) {
        this.elevatorGroupController = newElevatorGroupController;
    }
    
    
}
