package org.arosso.model;
/**
 * File generated from the model::Elevator uml Class
 * Generated by the Acceleo 3 <i>UML to Java</i> generator.
 */


import java.util.Vector;
// Start of user code (user defined imports)	

// End of user code

/**
 * http://intermediatetwo.webs.com/listening.htm  en 
 */
public class Elevator {
	

    public enum Direction{
    	UP, DOWN;
    }
	
    /**
     * Description of the property elevatorId.
     */
    public Integer elevatorId = 0;
    
    /**
     * Description of the property isInService.
     */
    public Integer isInService = 0;
    
    /**
     * Description of the property capacity.
     */
    public Integer capacity = 0;
    
    /**
     * Description of the property aceleration.
     */
    public Float aceleration = 0.0f;
    
    /**
     * Description of the property speed.
     */
    public Float speed = 0.0f;
    
    public Float jerk = 0.0f;
    
    /**
     * Description of the property doorCloseTime.
     */
    public Float doorCloseTime = 0.0f;
    
    /**
     * Description of the property doorOpenTime.
     */
    public Float doorOpenTime = 0.0f;
    
    /**
     * Description of the property passangerTransferTime.
     */
    public Float passangerTransferTime = 0.0f;
    
    /**
     * Description of the property numCurrentPassangers.
     */
    public Integer numCurrentPassangers = 0;
    
    /**
     * Description of the property restFloor.
     */
    public Integer restFloor = 0;
    
    /**
     * Description of the property isResting.
     */
    public Boolean isResting = true;
    
    /**
     * Description of the property passengers.
     */
    public Vector<Passenger> passengers = new Vector<Passenger>();
    
    public Direction direction = Direction.UP;
    
    /**
     * Description of the property position.
     */
    public Float position = 0.0f;
    
    public Direction dir;
    
    
    /**
     * The constructor.
     */
    public Elevator() {
    	// Start of user code constructor
    	super();
    	// End of user code
    }
    
    
    
    public Elevator(Integer elevatorId, Integer capacity, Float aceleration,
			Float speed, Float jerk, Float doorCloseTime, Float doorOpenTime,
			Float passangerTransferTime, Integer restFloor) {
		super();
		this.elevatorId = elevatorId;
		this.capacity = capacity;
		this.aceleration = aceleration;
		this.speed = speed;
		this.jerk = jerk;
		this.doorCloseTime = doorCloseTime;
		this.doorOpenTime = doorOpenTime;
		this.passangerTransferTime = passangerTransferTime;
		this.restFloor = restFloor;
	}



	/**
     * Description of the method move.
     */
    public void move() {
    	// Start of user code for method move
    	// End of user code
    }
     
     
    /**
     * Description of the method stop.
     */
    public void stop() {
    	// Start of user code for method stop
    	// End of user code
    }
     
    /**
     * Description of the method rest.
     */
    public void rest() {
    	// Start of user code for method rest
    	// End of user code
    }
    
    /**
     * Returns elevatorId.
     * @return elevatorId 
     */
    public Integer getElevatorId() {
    	return this.elevatorId;
    }
    
    /**
     * Sets a value to attribute elevatorId. 
     * @param newElevatorId 
     */
    public void setElevatorId(Integer newElevatorId) {
        this.elevatorId = newElevatorId;
    }
    
    /**
     * Returns isInService.
     * @return isInService 
     */
    public Integer getIsInService() {
    	return this.isInService;
    }
    
    /**
     * Sets a value to attribute isInService. 
     * @param newIsInService 
     */
    public void setIsInService(Integer newIsInService) {
        this.isInService = newIsInService;
    }
    
    /**
     * Returns capacity.
     * @return capacity 
     */
    public Integer getCapacity() {
    	return this.capacity;
    }
    
    /**
     * Sets a value to attribute capacity. 
     * @param newCapacity 
     */
    public void setCapacity(Integer newCapacity) {
        this.capacity = newCapacity;
    }
    
    /**
     * Returns aceleration.
     * @return aceleration 
     */
    public Float getAceleration() {
    	return this.aceleration;
    }
    
    /**
     * Sets a value to attribute aceleration. 
     * @param newAceleration 
     */
    public void setAceleration(Float newAceleration) {
        this.aceleration = newAceleration;
    }
    
    /**
     * Returns speed.
     * @return speed 
     */
    public Float getSpeed() {
    	return this.speed;
    }
    
    /**
     * Sets a value to attribute speed. 
     * @param newSpeed 
     */
    public void setSpeed(Float newSpeed) {
        this.speed = newSpeed;
    }
    
    /**
     * Returns doorCloseTime.
     * @return doorCloseTime 
     */
    public Float getDoorCloseTime() {
    	return this.doorCloseTime;
    }
    
    /**
     * Sets a value to attribute doorCloseTime. 
     * @param newDoorCloseTime 
     */
    public void setDoorCloseTime(Float newDoorCloseTime) {
        this.doorCloseTime = newDoorCloseTime;
    }
    
    /**
     * Returns doorOpenTime.
     * @return doorOpenTime 
     */
    public Float getDoorOpenTime() {
    	return this.doorOpenTime;
    }
    
    /**
     * Sets a value to attribute doorOpenTime. 
     * @param newDoorOpenTime 
     */
    public void setDoorOpenTime(Float newDoorOpenTime) {
        this.doorOpenTime = newDoorOpenTime;
    }
    
    /**
     * Returns passangerTransferTime.
     * @return passangerTransferTime 
     */
    public Float getPassangerTransferTime() {
    	return this.passangerTransferTime;
    }
    
    /**
     * Sets a value to attribute passangerTransferTime. 
     * @param newPassangerTransferTime 
     */
    public void setPassangerTransferTime(Float newPassangerTransferTime) {
        this.passangerTransferTime = newPassangerTransferTime;
    }
    
    /**
     * Returns numCurrentPassangers.
     * @return numCurrentPassangers 
     */
    public Integer getNumCurrentPassangers() {
    	return this.numCurrentPassangers;
    }
    
    /**
     * Sets a value to attribute numCurrentPassangers. 
     * @param newNumCurrentPassangers 
     */
    public void setNumCurrentPassangers(Integer newNumCurrentPassangers) {
        this.numCurrentPassangers = newNumCurrentPassangers;
    }
    
    /**
     * Returns direction.
     * @return direction 
     */
    public Direction getDirection() {
    	return this.direction;
    }
    
    /**
     * Sets a value to attribute direction. 
     * @param newDirection 
     */
    public void setDirection(Direction newDirection) {
        this.direction = newDirection;
    }
    
    /**
     * Returns restFloor.
     * @return restFloor 
     */
    public Integer getRestFloor() {
    	return this.restFloor;
    }
    
    /**
     * Sets a value to attribute restFloor. 
     * @param newRestFloor 
     */
    public void setRestFloor(Integer newRestFloor) {
        this.restFloor = newRestFloor;
    }
    
    /**
     * Returns isResting.
     * @return isResting 
     */
    public Boolean getIsResting() {
    	return this.isResting;
    }
    
    /**
     * Sets a value to attribute isResting. 
     * @param newIsResting 
     */
    public void setIsResting(Boolean newIsResting) {
        this.isResting = newIsResting;
    }
    
    /**
     * Returns passengers.
     * @return passengers 
     */
    public Vector<Passenger> getPassengers() {
    	return this.passengers;
    }
    
    /**
     * Sets a value to attribute passengers. 
     * @param newPassengers 
     */
    public void setPassengers(Vector<Passenger> newPassengers) {
        this.passengers = newPassengers;
    }
    
    /**
     * Returns position.
     * @return position 
     */
    public Float getPosition() {
    	return this.position;
    }
    
    /**
     * Sets a value to attribute position. 
     * @param newPosition 
     */
    public void setPosition(Float newPosition) {
        this.position = newPosition;
    }
    
    
}
