package org.arosso.model;

/**
 * File generated from the model::Floor uml Class
 * Generated by the Acceleo 3 <i>UML to Java</i> generator.
 */


// Start of user code (user defined imports)	

// End of user code

/**
 * Description of Floor.
 */
public class Floor {
    /**
     * Description of the property floorId.
     */
    public String floorId = "";
    
    /**
     * Description of the property population.
     */
    public Integer population = 0;
    
    /**
     * Description of the property isPortal.
     */
    public Boolean isPortal = true;
    
    /**
     * Description of the property floorName.
     */
    public String floorName = "";
    
    // Start of user code (user defined attributes)
    
    // End of user code
    
    /**
     * The constructor.
     */
    public Floor() {
    	// Start of user code constructor
    	super();
    	// End of user code
    }
    
    
    
    public Floor(String floorId, Integer population, Boolean isPortal,
			String floorName) {
		super();
		this.floorId = floorId;
		this.population = population;
		this.isPortal = isPortal;
		this.floorName = floorName;
	}



	// Start of user code (user defined methods)
    
    // End of user code
    
    /**
     * Returns floorId.
     * @return floorId 
     */
    public String getFloorId() {
    	return this.floorId;
    }
    
    /**
     * Sets a value to attribute floorId. 
     * @param newFloorId 
     */
    public void setFloorId(String newFloorId) {
        this.floorId = newFloorId;
    }
    
    /**
     * Returns population.
     * @return population 
     */
    public Integer getPopulation() {
    	return this.population;
    }
    
    /**
     * Sets a value to attribute population. 
     * @param newPopulation 
     */
    public void setPopulation(Integer newPopulation) {
        this.population = newPopulation;
    }
    
    /**
     * Returns isPortal.
     * @return isPortal 
     */
    public Boolean getIsPortal() {
    	return this.isPortal;
    }
    
    /**
     * Sets a value to attribute isPortal. 
     * @param newIsPortal 
     */
    public void setIsPortal(Boolean newIsPortal) {
        this.isPortal = newIsPortal;
    }
    
    /**
     * Returns floorName.
     * @return floorName 
     */
    public String getFloorName() {
    	return this.floorName;
    }
    
    /**
     * Sets a value to attribute floorName. 
     * @param newFloorName 
     */
    public void setFloorName(String newFloorName) {
        this.floorName = newFloorName;
    }
    
    
}
