/**
 * File generated from the model::Passenger uml Class
 * Generated by the Acceleo 3 <i>UML to Java</i> generator.
 */

package org.arosso.model;

import org.arosso.exception.CallIllegalState;

// Start of user code (user defined imports)	

// End of user code

/**
 * Description of Passenger.
 */
public class Passenger {
	
	public enum Type {
    	CALL, PASSENGER, MOCK_CALL;
    }
	
    /**
     * Description of the property arrivalTime.
     */
    private int arrivalTime = 0;
    
    /**
     * Description of the property pushedTime.
     */
    private Float pushedTime = 0.0f;
    
    /**
     * Description of the property pulledTime.
     */
    private Float pulledTime = 0.0f;
    
    /**
     * Description of the property originFloor.
     */
    private Integer originFloor = 0;
    
    /**
     * Description of the property destinationFloor.
     */
    private Integer destinationFloor = 0;
    
    /**
     * Description of the property assignedElevator.
     */
    private Integer assignedElevator = 0;
    
    /**
     * Type of call, for default is CALL the will be PASSENGER
     */
    private Type type = Type.CALL;
    
    // Start of user code (user defined attributes)
    
    // End of user code
    
    /**
     * The constructor.
     */
    private Passenger() {
    	// Start of user code constructor
    	super();
    	// End of user code
    }
    
    
    
    public Passenger(int arrivalTime, Integer originFloor,
			Integer destinationFloor, Type type) {
		super();
		this.arrivalTime = arrivalTime;
		this.originFloor = originFloor;
		this.destinationFloor = destinationFloor;
		this.type = type;
	}



	/**
     * Description of the method getTravelTime.
     * @return 
     */
    public Double getTravelTime() {
    	// Start of user code for method getTravelTime
    	Double getTravelTime = 0.0D;
    	return getTravelTime;
    	// End of user code
    }
     
    /**
     * Returns arrivalTime.
     * @return arrivalTime 
     */
    public int getArrivalTime() {
    	return this.arrivalTime;
    }
    
    /**
     * Sets a value to attribute arrivalTime. 
     * @param newArrivalTime 
     */
    public void setArrivalTime(int newArrivalTime) {
        this.arrivalTime = newArrivalTime;
    }
    
    /**
     * Returns pushedTime.
     * @return pushedTime 
     */
    public Float getPushedTime() {
    	return this.pushedTime;
    }
    
    /**
     * Sets a value to attribute pushedTime. 
     * @param newPushedTime 
     */
    public void setPushedTime(Float newPushedTime) {
        this.pushedTime = newPushedTime;
    }
    
    /**
     * Returns pulledTime.
     * @return pulledTime 
     */
    public Float getPulledTime() {
    	return this.pulledTime;
    }
    
    /**
     * Sets a value to attribute pulledTime. 
     * @param newPulledTime 
     */
    public void setPulledTime(Float newPulledTime) {
        this.pulledTime = newPulledTime;
    }
    
    /**
     * Returns originFloor.
     * @return originFloor 
     */
    public Integer getOriginFloor() {
    	return this.originFloor;
    }
    
    /**
     * Sets a value to attribute originFloor. 
     * @param newOriginFloor 
     */
    public void setOriginFloor(Integer newOriginFloor) {
        this.originFloor = newOriginFloor;
    }
    
    /**
     * Returns destinationFloor.
     * @return destinationFloor 
     */
    public Integer getDestinationFloor() {
    	return this.destinationFloor;
    }
    
    /**
     * Sets a value to attribute destinationFloor. 
     * @param newDestinationFloor 
     */
    public void setDestinationFloor(Integer newDestinationFloor) {
        this.destinationFloor = newDestinationFloor;
    }
    
    /**
     * Returns assignedElevator.
     * @return assignedElevator 
     */
    public Integer getAssignedElevator() {
    	return this.assignedElevator;
    }
    
    /**
     * Sets a value to attribute assignedElevator. 
     * @param newAssignedElevator 
     */
    public void setAssignedElevator(Integer newAssignedElevator) {
        this.assignedElevator = newAssignedElevator;
    }
    
    public Elevator.Direction getDirection(){
    	if(this.getOriginFloor()<this.getDestinationFloor()){
			return Elevator.Direction.UP;
		}else if(this.getOriginFloor()>this.getDestinationFloor()){
			return Elevator.Direction.DOWN;
		}else{
			new CallIllegalState("There is a call with no direction, it is so strange :S "+this);
			return Elevator.Direction.NONE;
		}
    }
    
    @Override
    public String toString() {
    	return "Po("+this.originFloor+") Pd("+this.destinationFloor+") "+" At("+this.arrivalTime+")";
    }

	public Type getType() {
		return type;
	}

	public void setType(Type type) {
		this.type = type;
	}
    
}
