/**
 * File generated from the model::ArrivalChecker uml Class
 * Generated by the Acceleo 3 <i>UML to Java</i> generator.
 */


import ;
// Start of user code (user defined imports)	

// End of user code

/**
 * Description of ArrivalChecker.
 */
public class ArrivalChecker extends SimulationRoutine implements SimulationRoutine {
    /**
     * Description of the property Property1.
     */
    public final Object Property1 = null;
    
    // Start of user code (user defined attributes)
    
    // End of user code
    
    /**
     * The constructor.
     */
    public ArrivalChecker() {
    	// Start of user code constructor
    	super();
    	// End of user code
    }
    
    // Start of user code (user defined methods)
    
    // End of user code
    
    /**
     * Returns Property1.
     * @return Property1 
     */
    public Object getProperty1() {
    	return this.Property1;
    }
    
    
}
