/**
 * File generated from the model::BasicTrafficModel uml Class
 * Generated by the Acceleo 3 <i>UML to Java</i> generator.
 */


import ;
// Start of user code (user defined imports)	

// End of user code

/**
 * Description of BasicTrafficModel.
 */
public class BasicTrafficModel implements TrafficModel {
    /**
     * Description of the property trafficDensity.
     */
    public Vector <> trafficDensity = null;
    
    // Start of user code (user defined attributes)
    
    // End of user code
    
    /**
     * The constructor.
     */
    public BasicTrafficModel() {
    	// Start of user code constructor
    	super();
    	// End of user code
    }
    
    /**
     * {@inheritDoc}
     * @see .TrafficModel
     *
     */
    public void getTrafficMode() {
    	// Start of user code for method getTrafficMode
    	return getTrafficMode;
    	// End of user code
    }
    
    /**
     * {@inheritDoc}
     * @see .TrafficModel
     *
     * @param time
     */
    public void getEstimatedPassengerNumber(Long time) {
    	// Start of user code for method getEstimatedPassengerNumber
    	return getEstimatedPassengerNumber;
    	// End of user code
    }
    
    /**
     * {@inheritDoc}
     * @see .TrafficModel
     *
     * @param time
     */
    public void getEstimatedDestinationFloor(Long time) {
    	// Start of user code for method getEstimatedDestinationFloor
    	return getEstimatedDestinationFloor;
    	// End of user code
    }
    
    /**
     * {@inheritDoc}
     * @see .TrafficModel
     *
     * @param time
     */
    public void getEstimatedOriginFloor(Long time) {
    	// Start of user code for method getEstimatedOriginFloor
    	return getEstimatedOriginFloor;
    	// End of user code
    }
    
    /**
     * {@inheritDoc}
     * @see .TrafficModel
     *
     * @param time
     */
    public void getEstimatedArrivalTime(Long time) {
    	// Start of user code for method getEstimatedArrivalTime
    	return getEstimatedArrivalTime;
    	// End of user code
    }
    
    // Start of user code (user defined methods)
    
    // End of user code
    
    /**
     * Returns trafficDensity.
     * @return trafficDensity 
     */
    public Vector <> getTrafficDensity() {
    	return this.trafficDensity;
    }
    
    /**
     * Sets a value to attribute trafficDensity. 
     * @param newTrafficDensity 
     */
    public void setTrafficDensity(Vector <> newTrafficDensity) {
        this.trafficDensity = newTrafficDensity;
    }
    
    
}
