/**
 * File generated from the model::Elevator uml Class
 * Generated by the Acceleo 3 <i>UML to Java</i> generator.
 */


import java.util.HashSet;
import ;
// Start of user code (user defined imports)	

// End of user code

/**
 * http://intermediatetwo.webs.com/listening.htm  en 
 */
public class Elevator {
    /**
     * Description of the property elevatorId.
     */
    public Integer elevatorId = 0;
    
    /**
     * Description of the property isInService.
     */
    public Integer isInService = 0;
    
    /**
     * Description of the property capacity.
     */
    public Integer capacity = 0;
    
    /**
     * Description of the property aceleration.
     */
    public Float aceleration = 0.0f;
    
    /**
     * Description of the property speed.
     */
    public Float speed = 0.0f;
    
    /**
     * Description of the property doorCloseTime.
     */
    public Float doorCloseTime = 0.0f;
    
    /**
     * Description of the property doorOpenTime.
     */
    public Float doorOpenTime = 0.0f;
    
    /**
     * Description of the property passangerTransferTime.
     */
    public Float passangerTransferTime = 0.0f;
    
    /**
     * Description of the property numCurrentPassangers.
     */
    public Integer numCurrentPassangers = 0;
    
    /**
     * Description of the property direction.
     */
    public Object direction = null;
    
    /**
     * Description of the property restFloor.
     */
    public Integer restFloor = 0;
    
    /**
     * Description of the property isResting.
     */
    public Boolean isResting = true;
    
    /**
     * Description of the property passengers.
     */
    public HashSet<Passenger> passengers = new HashSet<Passenger>();
    
    /**
     * Description of the property position.
     */
    public Float position = 0.0f;
    
    // Start of user code (user defined attributes)
    
    // End of user code
    
    /**
     * The constructor.
     */
    public Elevator() {
    	// Start of user code constructor
    	super();
    	// End of user code
    }
    
    /**
     * Description of the method move.
     */
    public void move() {
    	// Start of user code for method move
    	return move;
    	// End of user code
    }
     
    /**
     * Description of the method setDirection.
     */
    public void setDirection() {
    	// Start of user code for method setDirection
    	return setDirection;
    	// End of user code
    }
     
    /**
     * Description of the method stop.
     */
    public void stop() {
    	// Start of user code for method stop
    	return stop;
    	// End of user code
    }
     
    /**
     * Description of the method rest.
     */
    public void rest() {
    	// Start of user code for method rest
    	return rest;
    	// End of user code
    }
     
    // Start of user code (user defined methods)
    
    // End of user code
    
    /**
     * Returns elevatorId.
     * @return elevatorId 
     */
    public Integer getElevatorId() {
    	return this.elevatorId;
    }
    
    /**
     * Sets a value to attribute elevatorId. 
     * @param newElevatorId 
     */
    public void setElevatorId(Integer newElevatorId) {
        this.elevatorId = newElevatorId;
    }
    
    /**
     * Returns isInService.
     * @return isInService 
     */
    public Integer getIsInService() {
    	return this.isInService;
    }
    
    /**
     * Sets a value to attribute isInService. 
     * @param newIsInService 
     */
    public void setIsInService(Integer newIsInService) {
        this.isInService = newIsInService;
    }
    
    /**
     * Returns capacity.
     * @return capacity 
     */
    public Integer getCapacity() {
    	return this.capacity;
    }
    
    /**
     * Sets a value to attribute capacity. 
     * @param newCapacity 
     */
    public void setCapacity(Integer newCapacity) {
        this.capacity = newCapacity;
    }
    
    /**
     * Returns aceleration.
     * @return aceleration 
     */
    public Float getAceleration() {
    	return this.aceleration;
    }
    
    /**
     * Sets a value to attribute aceleration. 
     * @param newAceleration 
     */
    public void setAceleration(Float newAceleration) {
        this.aceleration = newAceleration;
    }
    
    /**
     * Returns speed.
     * @return speed 
     */
    public Float getSpeed() {
    	return this.speed;
    }
    
    /**
     * Sets a value to attribute speed. 
     * @param newSpeed 
     */
    public void setSpeed(Float newSpeed) {
        this.speed = newSpeed;
    }
    
    /**
     * Returns doorCloseTime.
     * @return doorCloseTime 
     */
    public Float getDoorCloseTime() {
    	return this.doorCloseTime;
    }
    
    /**
     * Sets a value to attribute doorCloseTime. 
     * @param newDoorCloseTime 
     */
    public void setDoorCloseTime(Float newDoorCloseTime) {
        this.doorCloseTime = newDoorCloseTime;
    }
    
    /**
     * Returns doorOpenTime.
     * @return doorOpenTime 
     */
    public Float getDoorOpenTime() {
    	return this.doorOpenTime;
    }
    
    /**
     * Sets a value to attribute doorOpenTime. 
     * @param newDoorOpenTime 
     */
    public void setDoorOpenTime(Float newDoorOpenTime) {
        this.doorOpenTime = newDoorOpenTime;
    }
    
    /**
     * Returns passangerTransferTime.
     * @return passangerTransferTime 
     */
    public Float getPassangerTransferTime() {
    	return this.passangerTransferTime;
    }
    
    /**
     * Sets a value to attribute passangerTransferTime. 
     * @param newPassangerTransferTime 
     */
    public void setPassangerTransferTime(Float newPassangerTransferTime) {
        this.passangerTransferTime = newPassangerTransferTime;
    }
    
    /**
     * Returns numCurrentPassangers.
     * @return numCurrentPassangers 
     */
    public Integer getNumCurrentPassangers() {
    	return this.numCurrentPassangers;
    }
    
    /**
     * Sets a value to attribute numCurrentPassangers. 
     * @param newNumCurrentPassangers 
     */
    public void setNumCurrentPassangers(Integer newNumCurrentPassangers) {
        this.numCurrentPassangers = newNumCurrentPassangers;
    }
    
    /**
     * Returns direction.
     * @return direction 
     */
    public Object getDirection() {
    	return this.direction;
    }
    
    /**
     * Sets a value to attribute direction. 
     * @param newDirection 
     */
    public void setDirection(Object newDirection) {
        this.direction = newDirection;
    }
    
    /**
     * Returns restFloor.
     * @return restFloor 
     */
    public Integer getRestFloor() {
    	return this.restFloor;
    }
    
    /**
     * Sets a value to attribute restFloor. 
     * @param newRestFloor 
     */
    public void setRestFloor(Integer newRestFloor) {
        this.restFloor = newRestFloor;
    }
    
    /**
     * Returns isResting.
     * @return isResting 
     */
    public Boolean getIsResting() {
    	return this.isResting;
    }
    
    /**
     * Sets a value to attribute isResting. 
     * @param newIsResting 
     */
    public void setIsResting(Boolean newIsResting) {
        this.isResting = newIsResting;
    }
    
    /**
     * Returns passengers.
     * @return passengers 
     */
    public HashSet<Passenger> getPassengers() {
    	return this.passengers;
    }
    
    /**
     * Sets a value to attribute passengers. 
     * @param newPassengers 
     */
    public void setPassengers(HashSet<Passenger> newPassengers) {
        this.passengers = newPassengers;
    }
    
    /**
     * Returns position.
     * @return position 
     */
    public Float getPosition() {
    	return this.position;
    }
    
    /**
     * Sets a value to attribute position. 
     * @param newPosition 
     */
    public void setPosition(Float newPosition) {
        this.position = newPosition;
    }
    
    
}
