/**
 * File generated from the model::ElevatorController uml Class
 * Generated by the Acceleo 3 <i>UML to Java</i> generator.
 */


import ;
import ;
// Start of user code (user defined imports)	

// End of user code

/**
 * Description of ElevatorController.
 */
public class ElevatorController extends SimulationRoutineElevator implements Observable, Observable {
    /**
     * Description of the property elevator.
     */
    public Object elevator = null;
    
    /**
     * Description of the property elevator.
     */
    public Elevator elevator = null;
    
    // Start of user code (user defined attributes)
    
    // End of user code
    
    /**
     * The constructor.
     */
    public ElevatorController() {
    	// Start of user code constructor
    	super();
    	// End of user code
    }
    
    // Start of user code (user defined methods)
    
    // End of user code
    
    /**
     * Returns elevator.
     * @return elevator 
     */
    public Object getElevator() {
    	return this.elevator;
    }
    
    /**
     * Sets a value to attribute elevator. 
     * @param newElevator 
     */
    public void setElevator(Object newElevator) {
        this.elevator = newElevator;
    }
    
    /**
     * Returns elevator.
     * @return elevator 
     */
    public Elevator getElevator() {
    	return this.elevator;
    }
    
    /**
     * Sets a value to attribute elevator. 
     * @param newElevator 
     */
    public void setElevator(Elevator newElevator) {
        this.elevator = newElevator;
    }
    
    
}
