/**
 * File generated from the model::SimulationProfile::Observer uml Interface
 * Generated by the Acceleo 3 <i>UML to Java</i> generator.
 */


// Start of user code (user defined imports)	

// End of user code

/**
 * Description of Observer.
 */
public interface Observer {
	// Start of user code (user defined attributes)
	
	// End of user code
	
	// Start of user code (user defined methods)
	
	// End of user code
}
