/**
 * File generated from the model::Passenger uml Class
 * Generated by the Acceleo 3 <i>UML to Java</i> generator.
 */


// Start of user code (user defined imports)	

// End of user code

/**
 * Description of Passenger.
 */
public class Passenger {
    /**
     * Description of the property arrivalTime.
     */
    public Float arrivalTime = 0.0f;
    
    /**
     * Description of the property pushedTime.
     */
    public Float pushedTime = 0.0f;
    
    /**
     * Description of the property pulledTime.
     */
    public Float pulledTime = 0.0f;
    
    /**
     * Description of the property originFloor.
     */
    public Integer originFloor = 0;
    
    /**
     * Description of the property destinationFloor.
     */
    public Integer destinationFloor = 0;
    
    /**
     * Description of the property assignedElevator.
     */
    public Integer assignedElevator = 0;
    
    // Start of user code (user defined attributes)
    
    // End of user code
    
    /**
     * The constructor.
     */
    public Passenger() {
    	// Start of user code constructor
    	super();
    	// End of user code
    }
    
    /**
     * Description of the method getTravelTime.
     * @return 
     */
    public Float getTravelTime() {
    	// Start of user code for method getTravelTime
    	Float getTravelTime = 0.0f;
    	return getTravelTime;
    	// End of user code
    }
     
    /**
     * Description of the method getArrivalTime.
     * @return 
     */
    public Float getArrivalTime() {
    	// Start of user code for method getArrivalTime
    	Float getArrivalTime = 0.0f;
    	return getArrivalTime;
    	// End of user code
    }
     
    /**
     * Description of the method getPulledTime.
     * @param pulled time 
     */
    public void getPulledTime(Float pulled time) {
    	// Start of user code for method getPulledTime
    	return getPulledTime;
    	// End of user code
    }
     
    // Start of user code (user defined methods)
    
    // End of user code
    
    /**
     * Returns arrivalTime.
     * @return arrivalTime 
     */
    public Float getArrivalTime() {
    	return this.arrivalTime;
    }
    
    /**
     * Sets a value to attribute arrivalTime. 
     * @param newArrivalTime 
     */
    public void setArrivalTime(Float newArrivalTime) {
        this.arrivalTime = newArrivalTime;
    }
    
    /**
     * Returns pushedTime.
     * @return pushedTime 
     */
    public Float getPushedTime() {
    	return this.pushedTime;
    }
    
    /**
     * Sets a value to attribute pushedTime. 
     * @param newPushedTime 
     */
    public void setPushedTime(Float newPushedTime) {
        this.pushedTime = newPushedTime;
    }
    
    /**
     * Returns pulledTime.
     * @return pulledTime 
     */
    public Float getPulledTime() {
    	return this.pulledTime;
    }
    
    /**
     * Sets a value to attribute pulledTime. 
     * @param newPulledTime 
     */
    public void setPulledTime(Float newPulledTime) {
        this.pulledTime = newPulledTime;
    }
    
    /**
     * Returns originFloor.
     * @return originFloor 
     */
    public Integer getOriginFloor() {
    	return this.originFloor;
    }
    
    /**
     * Sets a value to attribute originFloor. 
     * @param newOriginFloor 
     */
    public void setOriginFloor(Integer newOriginFloor) {
        this.originFloor = newOriginFloor;
    }
    
    /**
     * Returns destinationFloor.
     * @return destinationFloor 
     */
    public Integer getDestinationFloor() {
    	return this.destinationFloor;
    }
    
    /**
     * Sets a value to attribute destinationFloor. 
     * @param newDestinationFloor 
     */
    public void setDestinationFloor(Integer newDestinationFloor) {
        this.destinationFloor = newDestinationFloor;
    }
    
    /**
     * Returns assignedElevator.
     * @return assignedElevator 
     */
    public Integer getAssignedElevator() {
    	return this.assignedElevator;
    }
    
    /**
     * Sets a value to attribute assignedElevator. 
     * @param newAssignedElevator 
     */
    public void setAssignedElevator(Integer newAssignedElevator) {
        this.assignedElevator = newAssignedElevator;
    }
    
    
}
