/**
 * File generated from the model::SimulationModel uml Interface
 * Generated by the Acceleo 3 <i>UML to Java</i> generator.
 */


// Start of user code (user defined imports)	

// End of user code

/**
 * Description of SimulationModel.
 */
public interface SimulationModel {
	// Start of user code (user defined attributes)
    
    // End of user code
	
	// Start of user code (user defined methods)
    
    // End of user code
}
