/**
 * File generated from the model::StatisticsManager uml Class
 * Generated by the Acceleo 3 <i>UML to Java</i> generator.
 */


import ;
import ;
import ;
import ;
// Start of user code (user defined imports)	

// End of user code

/**
 * Description of StatisticsManager.
 */
public class StatisticsManager implements Observer {
    /**
     * Description of the property buildingSimulator.
     */
    public BuildingSimulator buildingSimulator = null;
    
    /**
     * Description of the property jasperReportManager.
     */
    public JasperReportManager jasperReportManager = null;
    
    // Start of user code (user defined attributes)
    
    // End of user code
    
    /**
     * The constructor.
     */
    public StatisticsManager() {
    	// Start of user code constructor
    	super();
    	// End of user code
    }
    
    /**
     * Description of the method generateServiceTimeReport.
     */
    public void generateServiceTimeReport() {
    	// Start of user code for method generateServiceTimeReport
    	return generateServiceTimeReport;
    	// End of user code
    }
     
    /**
     * Description of the method update.
     * @param obj 
     * @param arg 
     */
    public void update(Observable obj, Object arg) {
    	// Start of user code for method update
    	return update;
    	// End of user code
    }
     
    // Start of user code (user defined methods)
    
    // End of user code
    
    /**
     * Returns buildingSimulator.
     * @return buildingSimulator 
     */
    public BuildingSimulator getBuildingSimulator() {
    	return this.buildingSimulator;
    }
    
    /**
     * Sets a value to attribute buildingSimulator. 
     * @param newBuildingSimulator 
     */
    public void setBuildingSimulator(BuildingSimulator newBuildingSimulator) {
        this.buildingSimulator = newBuildingSimulator;
    }
    
    /**
     * Returns jasperReportManager.
     * @return jasperReportManager 
     */
    public JasperReportManager getJasperReportManager() {
    	return this.jasperReportManager;
    }
    
    /**
     * Sets a value to attribute jasperReportManager. 
     * @param newJasperReportManager 
     */
    public void setJasperReportManager(JasperReportManager newJasperReportManager) {
        this.jasperReportManager = newJasperReportManager;
    }
    
    
}
