/**
 * File generated from the model::TrafficGenerator uml Class
 * Generated by the Acceleo 3 <i>UML to Java</i> generator.
 */


import ;
import ;
// Start of user code (user defined imports)	

// End of user code

/**
 * Description of TrafficGenerator.
 */
public class TrafficGenerator extends SimulationRoutine {
    /**
     * Description of the property basicTrafficModel.
     */
    public BasicTrafficModel basicTrafficModel = null;
    
    // Start of user code (user defined attributes)
    
    // End of user code
    
    /**
     * The constructor.
     */
    public TrafficGenerator() {
    	// Start of user code constructor
    	super();
    	// End of user code
    }
    
    /**
     * Description of the method Operation1.
     */
    public void Operation1() {
    	// Start of user code for method Operation1
    	return Operation1;
    	// End of user code
    }
     
    /**
     * Description of the method calculateDestinationFloor.
     */
    public void calculateDestinationFloor() {
    	// Start of user code for method calculateDestinationFloor
    	return calculateDestinationFloor;
    	// End of user code
    }
     
    /**
     * Description of the method calculateOriginFloor.
     */
    public void calculateOriginFloor() {
    	// Start of user code for method calculateOriginFloor
    	return calculateOriginFloor;
    	// End of user code
    }
     
    /**
     * Description of the method calculateArrivalTime.
     */
    public void calculateArrivalTime() {
    	// Start of user code for method calculateArrivalTime
    	return calculateArrivalTime;
    	// End of user code
    }
     
    // Start of user code (user defined methods)
    
    // End of user code
    
    /**
     * Returns basicTrafficModel.
     * @return basicTrafficModel 
     */
    public BasicTrafficModel getBasicTrafficModel() {
    	return this.basicTrafficModel;
    }
    
    /**
     * Sets a value to attribute basicTrafficModel. 
     * @param newBasicTrafficModel 
     */
    public void setBasicTrafficModel(BasicTrafficModel newBasicTrafficModel) {
        this.basicTrafficModel = newBasicTrafficModel;
    }
    
    
}
