package org.arosso.sim;

import org.arosso.egcs.ElevatorGroupController;
import org.arosso.util.PropertiesBroker;
import org.arosso.util.PropertiesBroker.PROP_SET;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

/**
 * File generated from the model::ArrivalChecker uml Class
 * Generated by the Acceleo 3 <i>UML to Java</i> generator.
 */

// Start of user code (user defined imports)	

// End of user code

/**
 * Description of ArrivalChecker.
 */
public class ArrivalChecker extends SimulationRoutine {
    /**
     * Description of the property Property1.
     */
    public final Object Property1 = null;
    /**
     * Controller to assign calls to elevators
     */
    private ElevatorGroupController controller;

    
    /**
     * Logger
     */
    Logger logger = LoggerFactory.getLogger(this.getClass());
    
    /**
     * The constructor.
     * @throws Exception 
     */
    public ArrivalChecker(String name, Float activationTime ) throws Exception {
    	super( name,  activationTime);
    	logger.info("ArrivalChecker loaded!");
    	String egcsClass = PropertiesBroker.getInstance().getProperty(PROP_SET.SIMULATION,"egcsImplementation");
        ClassLoader classLoader = this.getClass().getClassLoader();
        Class myObjectClass = classLoader.loadClass(egcsClass);
        logger.debug("ArrivalChecker using EGCS "+myObjectClass);
        controller = (ElevatorGroupController) myObjectClass.newInstance();
    }
    
    @Override
    public void execute() {
    	logger.info("Checking for passangers arrivals");
    	if(true){
    		controller.assignCall();
    	}
    }
    
    
}
