package org.arosso.sim;

/**
 * File generated from the model::ArrivalChecker uml Class
 * Generated by the Acceleo 3 <i>UML to Java</i> generator.
 */

// Start of user code (user defined imports)	

// End of user code

/**
 * Description of ArrivalChecker.
 */
public class ArrivalChecker extends SimulationRoutine {
    /**
     * Description of the property Property1.
     */
    public final Object Property1 = null;

    
    /**
     * The constructor.
     */
    public ArrivalChecker() {
    	// Start of user code constructor
    	super();
    	// End of user code
    }
    
    
}
