package org.arosso.sim;
/**
 * File generated from the model::SimulationModel uml Interface
 * Generated by the Acceleo 3 <i>UML to Java</i> generator.
 */


// Start of user code (user defined imports)	

// End of user code

/**
 * Description of SimulationModel.
 */
public abstract class SimulationModel {
	
	private Double simulationClock=0D;
	
	private Integer delayTime=0;
	
	private Float deltaAdvaceTime=0F;
	
	private Long endSimulationTime=0L;

	public Double getSimulationClock() {
		return simulationClock;
	}

	public void setSimulationClock(Double simulationClock) {
		this.simulationClock = simulationClock;
	}

	public Integer getDelayTime() {
		return delayTime;
	}

	public void setDelayTime(Integer delayTime) {
		this.delayTime = delayTime;
	}

	public Float getDeltaAdvaceTime() {
		return deltaAdvaceTime;
	}

	public void setDeltaAdvaceTime(Float deltaAdvaceTime) {
		this.deltaAdvaceTime = deltaAdvaceTime;
	}

	public Long getEndSimulationTime() {
		return endSimulationTime;
	}

	public void setEndSimulationTime(Long endSimulationTime) {
		this.endSimulationTime = endSimulationTime;
	}
	
}
