package org.arosso.sim;

import java.util.Observable;

/**
 * File generated from the model::SimulationProfile::SimulationRoutine uml Class
 * Generated by the Acceleo 3 <i>UML to Java</i> generator.
 */


// Start of user code (user defined imports)	

// End of user code

/**
 * Description of SimulationRoutine.
 */
public class SimulationRoutine extends Observable {
    /**
     * Description of the property activationTime.
     */
    public Float activationTime = 0.0f;
    
    /**
     * Description of the property taskName.
     */
    public String taskName = "";
    
    /**
     * Description of the property nextRoutine.
     */
    public Object nextRoutine = null;
    
    /**
     * Description of the property DEFAULT_ACTIVATION_TIME.
     */
    public final Float DEFAULT_ACTIVATION_TIME = 0.0f;
    
    /**
     * Description of the property event.
     */
    public String event = "";
    
    /**
     * Description of the property routineName.
     */
    public String routineName = "";
    
    // Start of user code (user defined attributes)
    
    // End of user code
    
    /**
     * The constructor.
     */
    public SimulationRoutine() {
    	// Start of user code constructor
    	super();
    	// End of user code
    }
    
    /**
     * Description of the method execute.
     */
    public void execute() {
    	// Start of user code for method execute
    	// End of user code
    }
     
    /**
     * Description of the method setActivationTime.
     */
    public void setActivationTime() {
    	// Start of user code for method setActivationTime
    	// End of user code
    }
     
    // Start of user code (user defined methods)
    
    // End of user code
    
    /**
     * Returns activationTime.
     * @return activationTime 
     */
    public Float getActivationTime() {
    	return this.activationTime;
    }
    
    /**
     * Sets a value to attribute activationTime. 
     * @param newActivationTime 
     */
    public void setActivationTime(Float newActivationTime) {
        this.activationTime = newActivationTime;
    }
    
    /**
     * Returns taskName.
     * @return taskName 
     */
    public String getTaskName() {
    	return this.taskName;
    }
    
    /**
     * Sets a value to attribute taskName. 
     * @param newTaskName 
     */
    public void setTaskName(String newTaskName) {
        this.taskName = newTaskName;
    }
    
    /**
     * Returns nextRoutine.
     * @return nextRoutine 
     */
    public Object getNextRoutine() {
    	return this.nextRoutine;
    }
    
    /**
     * Sets a value to attribute nextRoutine. 
     * @param newNextRoutine 
     */
    public void setNextRoutine(Object newNextRoutine) {
        this.nextRoutine = newNextRoutine;
    }
    
    /**
     * Returns DEFAULT_ACTIVATION_TIME.
     * @return DEFAULT_ACTIVATION_TIME 
     */
    public Float getDEFAULT_ACTIVATION_TIME() {
    	return this.DEFAULT_ACTIVATION_TIME;
    }
    
    /**
     * Returns event.
     * @return event 
     */
    public String getEvent() {
    	return this.event;
    }
    
    /**
     * Sets a value to attribute event. 
     * @param newEvent 
     */
    public void setEvent(String newEvent) {
        this.event = newEvent;
    }
    
    /**
     * Returns routineName.
     * @return routineName 
     */
    public String getRoutineName() {
    	return this.routineName;
    }
    
    /**
     * Sets a value to attribute routineName. 
     * @param newRoutineName 
     */
    public void setRoutineName(String newRoutineName) {
        this.routineName = newRoutineName;
    }
    
    
    @Override
    public String toString() {
    	return this.routineName;
    }
    
}
