package org.arosso.sim;
/**
 * File generated from the model::SimulationModel uml Interface
 * Generated by the Acceleo 3 <i>UML to Java</i> generator.
 */


// Start of user code (user defined imports)	

// End of user code

/**
 * Description of SimulationModel.
 */
public interface SimulationModel {
	
	
}
