package org.arosso.sim;


/**
 * File generated from the model::SimulationProfile::SimulationRoutine uml Class
 * Generated by the Acceleo 3 <i>UML to Java</i> generator.
 */


// Start of user code (user defined imports)	

// End of user code

/**
 * Description of SimulationRoutine.
 */
public abstract class SimulationRoutine {
    /**
     * Description of the property activationTime.
     */
    public Float activationTime = 0.0f;
    
    /**
     * Description of the property routineName.
     */
    public String routineName = "";
    
    /**
     * The default constructor.
     */
    public SimulationRoutine() {
    	// Start of user code constructor
    	super();
    }
    
    /**
     * The constructor.
     */
    public SimulationRoutine(String name, Float activationTime) {
    	// Start of user code constructor
    	super();
    	this.routineName = name;
    	this.activationTime = activationTime;
    }
    
    
    /**
     * Description of the method execute.
     */
    public abstract void execute();
    
    /**
     * Returns activationTime.
     * @return activationTime 
     */
    public Float getActivationTime() {
    	return this.activationTime;
    }
    
    /**
     * Sets a value to attribute activationTime. 
     * @param newActivationTime 
     */
    public void setActivationTime(Float newActivationTime) {
        this.activationTime = newActivationTime;
    }
    
    
    /**
     * Returns routineName.
     * @return routineName 
     */
    public String getRoutineName() {
    	return this.routineName;
    }
    
    /**
     * Sets a value to attribute routineName. 
     * @param newRoutineName 
     */
    public void setRoutineName(String newRoutineName) {
        this.routineName = newRoutineName;
    }
    
    
    @Override
    public String toString() {
    	return this.routineName;
    }
    
}
