
package org.arosso.sim;

/**
 * File generated from the model::TrafficModel uml Interface
 * Generated by the Acceleo 3 <i>UML to Java</i> generator.
 */


// Start of user code (user defined imports)	

// End of user code

/**
 * Description of TrafficModel.
 */
public interface TrafficModel {
	// Start of user code (user defined attributes)
	
	// End of user code
	
	/**
	 * Description of the method getEstimatedPassengerNumber.
	 * @param time 
	 */
	public void getEstimatedPassengerNumber(Long time);
	
	/**
	 * Description of the method getEstimatedOriginFloor.
	 * @param time 
	 */
	public void getEstimatedOriginFloor(Long time);
	
	/**
	 * Description of the method getEstimatedDestinationFloor.
	 * @param time 
	 */
	public void getEstimatedDestinationFloor(Long time);
	
	/**
	 * Description of the method getEstimatedArrivalTime.
	 * @param time 
	 */
	public void getEstimatedArrivalTime(Long time);
	
	/**
	 * Description of the method getTrafficMode.
	 */
	public void getTrafficMode();
	
	// Start of user code (user defined methods)
	
	// End of user code
}
