
package org.arosso.sim;

/**
 * File generated from the model::TrafficModel uml Interface
 * Generated by the Acceleo 3 <i>UML to Java</i> generator.
 */


// Start of user code (user defined imports)	

// End of user code

/**
 * Description of TrafficModel.
 */
public interface TrafficModel {
	// Start of user code (user defined attributes)
	
	// End of user code
	
	/**
	 * Description of the method getEstimatedPassengerNumber.
	 * @param time 
	 */
	public int getEstimatedPassengerNumber(Float time);
	
	/**
	 * Description of the method getEstimatedOriginFloor.
	 * @param time 
	 */
	public int getEstimatedOriginFloor(Float time);
	
	/**
	 * Description of the method getEstimatedDestinationFloor.
	 * @param time 
	 */
	public int getEstimatedDestinationFloor(Float time);
	
	/**
	 * Description of the method getEstimatedArrivalTime.
	 * @param time 
	 */
	public Float getEstimatedArrivalTime(Float time);
	
	/**
	 * Description of the method getTrafficMode.
	 */
	public String getTrafficMode();
	
}
