package org.arosso.stats;
/**
 * File generated from the model::JasperReportManager uml Class
 * Generated by the Acceleo 3 <i>UML to Java</i> generator.
 */


// Start of user code (user defined imports)	

// End of user code

/**
 * Description of JasperReportManager.
 */
public class JasperReportManager {
    // Start of user code (user defined attributes)
    
    // End of user code
    
    /**
     * The constructor.
     */
    public JasperReportManager() {
    	// Start of user code constructor
    	super();
    	// End of user code
    }
    
    /**
     * Description of the method generateJasperReport.
     */
    public void generateJasperReport() {
    	// Start of user code for method generateJasperReport
    	// End of user code
    }
     
    // Start of user code (user defined methods)
    
    // End of user code
    
    
}
