package org.arosso.gui;

/**
 * File generated from the model::GuiController uml Class
 * Generated by the Acceleo 3 <i>UML to Java</i> generator.
 */


// Start of user code (user defined imports)	

// End of user code

/**
 * Description of GuiController.
 */
public class GuiController {
    /**
     * Description of the property commandBox.
     */
    public CommandShell commandBox = null;
    
    // Start of user code (user defined attributes)
    
    // End of user code
    
    /**
     * The constructor.
     */
    public GuiController() {
    	// Start of user code constructor
    	super();
    	// End of user code
    }
    
    /**
     * Description of the method viewSimulationConfig.
     */
    public void viewSimulationConfig() {
    	// Start of user code for method viewSimulationConfig
    	// End of user code
    }
     
    /**
     * Description of the method readFromCommandLine.
     */
    public void readFromCommandLine() {
    	// Start of user code for method readFromCommandLine
    	// End of user code
    }
     
    /**
     * Description of the method startSimulation.
     */
    public void startSimulation() {
    	// Start of user code for method startSimulation
    	// End of user code
    }
     
    /**
     * Description of the method pauseSimulation.
     */
    public void pauseSimulation() {
    	// Start of user code for method pauseSimulation
    	// End of user code
    }
     
    /**
     * Description of the method stopSimulation.
     */
    public void stopSimulation() {
    	// Start of user code for method stopSimulation
    	// End of user code
    }
     
    /**
     * Description of the method finish.
     */
    public void finish() {
    	// Start of user code for method finish
    	// End of user code
    }
     
    /**
     * Description of the method init.
     */
    public void init() {
    	// Start of user code for method init
    	// End of user code
    }
     
    // Start of user code (user defined methods)
    
    // End of user code
    
    /**
     * Returns commandBox.
     * @return commandBox 
     */
    public CommandShell getCommandBox() {
    	return this.commandBox;
    }
    
    /**
     * Sets a value to attribute commandBox. 
     * @param newCommandBox 
     */
    public void setCommandBox(CommandShell newCommandBox) {
        this.commandBox = newCommandBox;
    }
    
    
}
