package org.arosso.egcs;
import org.arosso.sim.RoutineManager;
import org.arosso.sim.SimulationRoutine;

/**
 * File generated from the model::conventionalElevatorGroupController uml Class
 * Generated by the Acceleo 3 <i>UML to Java</i> generator.
 */


/**
 * Description of conventionalElevatorGroupController.
 */
public class conventionalElevatorGroupController extends SimulationRoutine implements ElevatorGroupController {
    /**
     * Description of the property rutineManager.
     */
    public RoutineManager rutineManager = null;
    
    // Start of user code (user defined attributes)
    
    // End of user code
    
    /**
     * The constructor.
     */
    public conventionalElevatorGroupController() {
    	// Start of user code constructor
    	super();
    	// End of user code
    }
    
    /**
     * Description of the method assignCallToElevator.
     */
    public void assignCallToElevator() {
    	// Start of user code for method assignCallToElevator
    	// End of user code
    }
     
    /**
     * {@inheritDoc}
     * @see .ElevatorGroupController
     *
     */
    public void AssignCallToElevator() {
    	// Start of user code for method AssignCallToElevator
    	// End of user code
    }
    
    // Start of user code (user defined methods)
    
    // End of user code
    
    /**
     * Returns rutineManager.
     * @return rutineManager
     */
    public RoutineManager getRutineManager() {
    	return this.rutineManager;
    }
    
    /**
     * Sets a value to attribute rutineManager. 
     * @param newRutineManager
     */
    public void setRutineManager(RoutineManager newRutineManager) {
        this.rutineManager = newRutineManager;
    }
    
    
}
