package org.arosso.egcs;
/**
 * File generated from the model::ElevatorGroupController uml Interface
 * Generated by the Acceleo 3 <i>UML to Java</i> generator.
 */


// Start of user code (user defined imports)	

// End of user code

/**
 * Description of ElevatorGroupController.
 */
public interface ElevatorGroupController {
	/**
	 * Description of the property .
	 */
	
	// Start of user code (user defined attributes)
	
	// End of user code
	
	/**
	 * Description of the method AssignCallToElevator.
	 */
	public void assignCall();
	
	// Start of user code (user defined methods)
	
	// End of user code
}
